#!/usr/bin/env bash
# Automate Nginx installation
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
echo -e "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start
