#!/usr/bin/env bash
# Script to configure a new ubuntu machine

sudo apt-get update
sudo apt-get install -y nginx
sudo sed -i 's/http {/&\n\tadd_header X-Served-By $HOSTNAME;/' /etc/nginx/nginx.conf
sudo service nginx start
